# Generated by Django 5.2.13 on 2026-04-07 21:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='кличка')),
                ('species', models.CharField(choices=[('cat', 'Кошка'), ('dog', 'Собака'), ('bird', 'Птица'), ('rodent', 'Грызун'), ('reptile', 'Рептилия'), ('other', 'Другое')], max_length=20, verbose_name='вид')),
                ('breed', models.CharField(blank=True, max_length=100, verbose_name='порода')),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(360)], verbose_name='возраст (мес.)')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(999.99)], verbose_name='вес (кг)')),
                ('health_notes', models.TextField(blank=True, verbose_name='заметки о здоровье')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='pets/', verbose_name='фото')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='добавлен')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL, verbose_name='владелец')),
            ],
            options={
                'verbose_name': 'питомец',
                'verbose_name_plural': 'питомцы',
                'ordering': ['name'],
            },
        ),
    ]
