# Generated by Django 5.2.13 on 2026-04-07 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('pets', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='дата приёма')),
                ('time_slot', models.TimeField(verbose_name='время')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('confirmed', 'Подтверждена'), ('in_progress', 'В процессе'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='pending', max_length=20, verbose_name='статус')),
                ('comment', models.TextField(blank=True, verbose_name='комментарий')),
                ('cancel_reason', models.TextField(blank=True, verbose_name='причина отмены')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлена')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL, verbose_name='клиент')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='doctors.doctor', verbose_name='врач')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='pets.pet', verbose_name='питомец')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='services.service', verbose_name='услуга')),
            ],
            options={
                'verbose_name': 'запись на приём',
                'verbose_name_plural': 'записи на приём',
                'ordering': ['-date', '-time_slot'],
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField(verbose_name='диагноз')),
                ('treatment', models.TextField(blank=True, verbose_name='лечение')),
                ('recommendations', models.TextField(blank=True, verbose_name='рекомендации')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='medical_records/', verbose_name='файл (анализы)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создана')),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_record', to='appointments.appointment', verbose_name='запись на приём')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='doctors.doctor', verbose_name='врач')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='pets.pet', verbose_name='питомец')),
            ],
            options={
                'verbose_name': 'медицинская карта',
                'verbose_name_plural': 'медицинские карты',
                'ordering': ['-created_at'],
            },
        ),
    ]
