# Generated by Django 5.2.13 on 2026-04-21 15:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='medical_records/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='файл (анализы)'),
        ),
    ]
