# Generated by Django 5.2.13 on 2026-04-21 17:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def backfill_record_date(apps, schema_editor):
    MedicalRecord = apps.get_model('appointments', 'MedicalRecord')
    for record in MedicalRecord.objects.all():
        if record.appointment_id:
            record.date = record.appointment.date
        else:
            record.date = record.created_at.date()
        record.save(update_fields=['date'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_medicalrecord_attachment'),
        ('doctors', '0002_alter_doctor_photo_alter_specialty_icon'),
        ('pets', '0002_alter_pet_photo'),
        ('services', '0002_alter_service_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalrecord',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'запись в медкарте', 'verbose_name_plural': 'медицинские карты'},
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='дата записи'),
        ),
        migrations.RunPython(backfill_record_date, noop),
        migrations.AlterField(
            model_name='medicalrecord',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_record', to='appointments.appointment', verbose_name='приём'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medical_records', to='doctors.doctor', verbose_name='врач'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'confirmed', 'in_progress'])), fields=('doctor', 'date', 'time_slot'), name='unique_active_slot_per_doctor'),
        ),
    ]
