# Generated by Django 5.2.13 on 2026-04-07 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='название')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='specialties/', verbose_name='иконка')),
            ],
            options={
                'verbose_name': 'специализация',
                'verbose_name_plural': 'специализации',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name='стаж (лет)')),
                ('education', models.TextField(blank=True, verbose_name='образование')),
                ('bio', models.TextField(blank=True, verbose_name='о враче')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='doctors/', verbose_name='фото')),
                ('photo_url', models.URLField(blank=True, verbose_name='ссылка на фото')),
                ('consultation_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='цена консультации')),
                ('is_available', models.BooleanField(default=True, verbose_name='доступен')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'врач',
                'verbose_name_plural': 'врачи',
                'ordering': ['-experience_years'],
            },
        ),
        migrations.CreateModel(
            name='DoctorSpecialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, verbose_name='основная')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor', verbose_name='врач')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.specialty', verbose_name='специализация')),
            ],
            options={
                'verbose_name': 'специализация врача',
                'verbose_name_plural': 'специализации врачей',
                'unique_together': {('doctor', 'specialty')},
            },
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialties',
            field=models.ManyToManyField(blank=True, related_name='doctors', through='doctors.DoctorSpecialty', to='doctors.specialty', verbose_name='специализации'),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], verbose_name='день недели')),
                ('start_time', models.TimeField(verbose_name='начало')),
                ('end_time', models.TimeField(verbose_name='конец')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='doctors.doctor', verbose_name='врач')),
            ],
            options={
                'verbose_name': 'расписание',
                'verbose_name_plural': 'расписания',
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('doctor', 'day_of_week')},
            },
        ),
    ]
