# Generated by Django 5.2.13 on 2026-04-21 15:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='doctors/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='фото'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='specialties/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'svg', 'webp'])], verbose_name='иконка'),
        ),
    ]
