# Generated by Django 5.2.13 on 2026-04-21 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_alter_doctor_photo_alter_specialty_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='photo_url',
        ),
    ]
